name: 'medicare_utils'
channels:
    - conda-forge
dependencies:
    - arrow>=0.12.1
    - bumpversion==0.5.3
    - coverage==4.5.1
    - cython>=0.28.3
    - dask>=0.18.0
    - fastparquet>=0.1.5
    - flake8>=3.5.0
    - ipykernel>=4.8.2
    - joblib
    - jupyter
    - matplotlib>=2.2.2
    - mkdocs>=0.17.4
    - mypy
    - numpy>=1.14.5
    - pandas>=0.23.1
    - pip==9.0.1
    - pyarrow>=0.9.0
    - pydocstyle>=2.1.1
    - pytest>=3.6.2
    - python-dateutil>=2.7.3
    - python-snappy>=0.5.2
    - python=3.6
    - pytz>=2018.4
    - recommonmark>=0.4.0
    - requests>=2.19.1
    - seaborn>=0.8.1
    - sphinx>=1.7.5
    - tox==2.9.1
    - tqdm>=4.23.4
    - wheel==0.30.0
    - yapf>=0.22.0
    - pip:
        - -e .
        - mkdocs-material>=2.9.1
        - pymdown-extensions>=4.11
        - python-language-server>=0.19.0
        - requests-html
