name: 'medicare_utils'
channels:
    - conda-forge
dependencies:
    - bumpversion==0.5.3
    - dask>=0.18.0
    - fastparquet>=0.1.5
    - flake8>=3.5.0
    - ipykernel>=4.8.2
    - joblib
    - jupyter
    - mypy
    - numpy>=1.14.5
    - pandas>=0.23.3
    - pip
    - pyarrow>=0.10.0
    - pydocstyle>=2.1.1
    - pytest>=3.6.2
    - python-snappy>=0.5.2
    - python=3.6
    - recommonmark>=0.4.0
    - requests>=2.19.1
    - sphinx>=1.7.5
    - tqdm>=4.23.4
    - wheel==0.30.0
    - yapf>=0.22.0
    - pip:
        - pymdown-extensions>=4.11
        - python-language-server>=0.19.0
        - requests-html
        - sphinx-autodoc-typehints
        - sphinx-bootstrap-theme
